sudo: required
services:
  - docker

before_install:
  - docker build -t umutyilmaz/docker-react-new -f Dockerfile.dev .

script:
  - docker run -e CI=true umutyilmaz/docker-react-new npm run test -- --coverage